"""Seed an offline demo: original synthetic challenges, demo users and simulated duels.

Everything here is generated: the songs are synthesized tones, the references are
procedural stick figures, and the duel results come from synthetic players. The
dashboards will therefore show illustrative data, never real results.

    python -m scripts.seed_demo            # refuses if users already exist
    python -m scripts.seed_demo --reset    # wipes backend/data first
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
import wave
from datetime import timedelta
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import select  # noqa: E402

from app import auth, duels  # noqa: E402
from app.config import settings  # noqa: E402
from app.dashboard import week_bounds  # noqa: E402
from app.db import Database  # noqa: E402
from app.models import Attempt, Duel, User, utcnow  # noqa: E402
from app.publish import publish_version  # noqa: E402
from app.scoring import ChallengeSpec, ScoringConfig, score_attempt  # noqa: E402
from app.scoring.synthetic import SyntheticRoutine  # noqa: E402

DEMO_PASSWORD = "dance-duel-demo"
USERS = {  # name: (typical delay s, noise px, amplitude) -> a rough "skill" profile
    "alice": (0.05, 2.0, 0.95),
    "bob": (0.15, 3.0, 0.85),
    "carol": (0.10, 2.5, 0.90),
    "dave": (0.25, 4.0, 0.75),
    "erin": (0.20, 3.5, 0.80),
}
CHALLENGES = [
    # slug, title, description, difficulty, seed, duration, beat, signature windows
    ("demo-groove", "Demo Groove", "Upbeat arm-and-step routine at 120 BPM.", "easy", 3, 20.0, 0.5, ((4.0, 6.0),)),
    ("robot-hits", "Robot Hits", "Sharp stops on every other beat.", "medium", 11, 16.0, 0.5, ((8.0, 10.0),)),
    ("slow-wave", "Slow Wave", "Flowing arms at 80 BPM.", "easy", 21, 24.0, 0.75, ()),
]


def synth_song(path: Path, duration_s: float, beat_s: float, seed: int, rate: int = 22050) -> None:
    """A short original tune: pentatonic notes on each beat plus a click track."""
    rng = np.random.default_rng(seed)
    t = np.arange(int(duration_s * rate)) / rate
    audio = np.zeros_like(t)
    scale = 220.0 * 2 ** (np.array([0, 2, 4, 7, 9, 12, 14, 16]) / 12)
    for i, start in enumerate(np.arange(0, duration_s, beat_s)):
        a, b = int(start * rate), int(min(duration_s, start + beat_s) * rate)
        seg = t[a:b] - start
        env = np.exp(-3.0 * seg / beat_s)
        audio[a:b] += 0.25 * env * np.sin(2 * np.pi * rng.choice(scale) * seg)
        audio[a:b] += 0.12 * env * np.sin(2 * np.pi * scale[0] / 2 * seg)
        click = int(0.015 * rate)
        audio[a : a + click] += (0.5 if i % 4 == 0 else 0.3) * np.sin(2 * np.pi * 1500 * seg[:click])
    pcm = (np.clip(audio, -1, 1) * 32767).astype(np.int16)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(pcm.tobytes())


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--reset", action="store_true", help="delete backend/data before seeding")
    p.add_argument("--duels", type=int, default=14)
    args = p.parse_args()

    if args.reset and settings.data_dir.exists():
        shutil.rmtree(settings.data_dir)
    settings.ensure_dirs()
    database = Database(settings.database_url)
    database.create_all()
    rng = np.random.default_rng(42)

    with database.session() as db:
        if db.scalar(select(User)):
            sys.exit("Database already has users. Re-run with --reset to start over.")

        users = {name: User(username=name, password_hash=auth.hash_password(DEMO_PASSWORD), rating=1000.0) for name in USERS}
        db.add_all(users.values())
        db.flush()

        versions, routines = [], []
        with tempfile.TemporaryDirectory() as tmp:
            for slug, title, desc, diff, seed, dur, beat, windows in CHALLENGES:
                routine = SyntheticRoutine(seed=seed, duration_s=dur, beat_s=beat)
                song = Path(tmp) / f"{slug}.wav"
                synth_song(song, dur, beat, seed)
                spec = ChallengeSpec(events=routine.events(every_beats=4 if beat < 0.6 else 2), signature_windows=windows, config=ScoringConfig())
                version = publish_version(
                    db, settings, slug=slug, title=title, description=desc, difficulty=diff,
                    song_file=song, reference=routine.sample(), spec=spec,
                    pose_model="synthetic-stick-figure", license_note="Original synthetic demo asset generated by seed_demo.py.",
                )  # fmt: skip
                versions.append(version)
                routines.append(routine)
        db.commit()

        def play(user: User, version, routine, duel: Duel, at) -> Attempt:
            delay, noise, amp = USERS[user.username]
            seq = routine.sample(
                delay_s=float(rng.normal(delay, 0.05)),
                noise_px=noise,
                amplitude=float(np.clip(rng.normal(amp, 0.05), 0.5, 1.0)),
                scale_px=float(rng.uniform(110, 170)),
                seed=int(rng.integers(1e9)),
            )
            res = score_attempt(routine.sample(), seq, ChallengeSpec.from_dict(version.spec))
            a = Attempt(
                user_id=user.id, challenge_version_id=version.id, duel_id=duel.id, mode="official",
                status="scored" if res.valid else "invalid", created_at=at, uploaded_at=at, analyzed_at=at,
                pose_score=res.pose, timing_score=res.timing, dynamics_score=res.dynamics, flow_score=res.flow,
                total_score=res.total, analysis_version=res.analysis_version,
                details={"coverage": res.coverage, "events": [e.__dict__ for e in res.events], "timeline": res.timeline, "feedback": res.feedback},
            )  # fmt: skip
            db.add(a)
            db.flush()
            return a

        now = utcnow()
        week_start, _ = week_bounds(now, settings.timezone)
        names = list(USERS)
        for _ in range(args.duels):
            x, y = rng.choice(len(names), 2, replace=False)
            ci = int(rng.choice(len(versions), p=[0.5, 0.3, 0.2]))
            at = week_start + (now - week_start) * float(rng.uniform(0.05, 0.95))
            duel = duels.create_duel(db, users[names[x]], users[names[y]], versions[ci], at, settings)
            duels.accept(db, duel, users[names[y]], at)
            for u in (users[names[x]], users[names[y]]):
                duels.on_attempt_finished(db, play(u, versions[ci], routines[ci], duel, at), at, settings)
            db.commit()

        # Open duels so the UI has something to act on.
        duels.create_duel(db, users["dave"], users["alice"], versions[0], now - timedelta(hours=1), settings)
        waiting = duels.create_duel(db, users["alice"], users["bob"], versions[1], now - timedelta(hours=2), settings)
        duels.accept(db, waiting, users["bob"], now - timedelta(hours=2))
        duels.on_attempt_finished(db, play(users["bob"], versions[1], routines[1], waiting, now), now, settings)
        db.commit()

        print(f"Seeded {len(versions)} challenges, {len(users)} users, {args.duels} finalized duels.")
        print(f"Sign in as any of {', '.join(USERS)} with password '{DEMO_PASSWORD}'.")
        for u in sorted(users.values(), key=lambda u: -u.rating):
            print(f"  {u.username:6s} rating {u.rating:7.1f}")


if __name__ == "__main__":
    main()
